- hosts: ['dockerd']
  tasks:
    - name: Pull nginx image
      docker_image:
        name: nginx
        source: pull
        state: present
        tag: mainline

    - name: Run nginx container
      docker_container:
        name: webapp
        image: nginx:mainline
        state: started
        published_ports:
          - "80:80"
        restart_policy: always
